// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEEnemyData : IGDEData
    {
        static string IDKey = "ID";
		int _ID;
        public int ID
        {
            get { return _ID; }
            set {
                if (_ID != value)
                {
                    _ID = value;
					GDEDataManager.SetInt(_key, IDKey, _ID);
                }
            }
        }

        static string MaxHPKey = "MaxHP";
		int _MaxHP;
        public int MaxHP
        {
            get { return _MaxHP; }
            set {
                if (_MaxHP != value)
                {
                    _MaxHP = value;
					GDEDataManager.SetInt(_key, MaxHPKey, _MaxHP);
                }
            }
        }

        static string MoveVecKey = "MoveVec";
		float _MoveVec;
        public float MoveVec
        {
            get { return _MoveVec; }
            set {
                if (_MoveVec != value)
                {
                    _MoveVec = value;
					GDEDataManager.SetFloat(_key, MoveVecKey, _MoveVec);
                }
            }
        }

        static string AlertRangeKey = "AlertRange";
		float _AlertRange;
        public float AlertRange
        {
            get { return _AlertRange; }
            set {
                if (_AlertRange != value)
                {
                    _AlertRange = value;
					GDEDataManager.SetFloat(_key, AlertRangeKey, _AlertRange);
                }
            }
        }

        static string AtkRangeKey = "AtkRange";
		float _AtkRange;
        public float AtkRange
        {
            get { return _AtkRange; }
            set {
                if (_AtkRange != value)
                {
                    _AtkRange = value;
					GDEDataManager.SetFloat(_key, AtkRangeKey, _AtkRange);
                }
            }
        }

        static string AtkIntervalKey = "AtkInterval";
		float _AtkInterval;
        public float AtkInterval
        {
            get { return _AtkInterval; }
            set {
                if (_AtkInterval != value)
                {
                    _AtkInterval = value;
					GDEDataManager.SetFloat(_key, AtkIntervalKey, _AtkInterval);
                }
            }
        }

        static string HurtProtectKey = "HurtProtect";
		float _HurtProtect;
        public float HurtProtect
        {
            get { return _HurtProtect; }
            set {
                if (_HurtProtect != value)
                {
                    _HurtProtect = value;
					GDEDataManager.SetFloat(_key, HurtProtectKey, _HurtProtect);
                }
            }
        }

        static string MassKey = "Mass";
		float _Mass;
        public float Mass
        {
            get { return _Mass; }
            set {
                if (_Mass != value)
                {
                    _Mass = value;
					GDEDataManager.SetFloat(_key, MassKey, _Mass);
                }
            }
        }

        static string PrefabPathKey = "PrefabPath";
		string _PrefabPath;
        public string PrefabPath
        {
            get { return _PrefabPath; }
            set {
                if (_PrefabPath != value)
                {
                    _PrefabPath = value;
					GDEDataManager.SetString(_key, PrefabPathKey, _PrefabPath);
                }
            }
        }

        public GDEEnemyData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "Enemy");
			
            dict.Merge(true, ID.ToGDEDict(IDKey));
            dict.Merge(true, MaxHP.ToGDEDict(MaxHPKey));
            dict.Merge(true, MoveVec.ToGDEDict(MoveVecKey));
            dict.Merge(true, AlertRange.ToGDEDict(AlertRangeKey));
            dict.Merge(true, AtkRange.ToGDEDict(AtkRangeKey));
            dict.Merge(true, AtkInterval.ToGDEDict(AtkIntervalKey));
            dict.Merge(true, HurtProtect.ToGDEDict(HurtProtectKey));
            dict.Merge(true, Mass.ToGDEDict(MassKey));
            dict.Merge(true, PrefabPath.ToGDEDict(PrefabPathKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(IDKey, out _ID);
                dict.TryGetInt(MaxHPKey, out _MaxHP);
                dict.TryGetFloat(MoveVecKey, out _MoveVec);
                dict.TryGetFloat(AlertRangeKey, out _AlertRange);
                dict.TryGetFloat(AtkRangeKey, out _AtkRange);
                dict.TryGetFloat(AtkIntervalKey, out _AtkInterval);
                dict.TryGetFloat(HurtProtectKey, out _HurtProtect);
                dict.TryGetFloat(MassKey, out _Mass);
                dict.TryGetString(PrefabPathKey, out _PrefabPath);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _ID = GDEDataManager.GetInt(_key, IDKey, _ID);
            _MaxHP = GDEDataManager.GetInt(_key, MaxHPKey, _MaxHP);
            _MoveVec = GDEDataManager.GetFloat(_key, MoveVecKey, _MoveVec);
            _AlertRange = GDEDataManager.GetFloat(_key, AlertRangeKey, _AlertRange);
            _AtkRange = GDEDataManager.GetFloat(_key, AtkRangeKey, _AtkRange);
            _AtkInterval = GDEDataManager.GetFloat(_key, AtkIntervalKey, _AtkInterval);
            _HurtProtect = GDEDataManager.GetFloat(_key, HurtProtectKey, _HurtProtect);
            _Mass = GDEDataManager.GetFloat(_key, MassKey, _Mass);
            _PrefabPath = GDEDataManager.GetString(_key, PrefabPathKey, _PrefabPath);
        }

        public GDEEnemyData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEEnemyData newClone = new GDEEnemyData(newKey);

            newClone.ID = ID;
            newClone.MaxHP = MaxHP;
            newClone.MoveVec = MoveVec;
            newClone.AlertRange = AlertRange;
            newClone.AtkRange = AtkRange;
            newClone.AtkInterval = AtkInterval;
            newClone.HurtProtect = HurtProtect;
            newClone.Mass = Mass;
            newClone.PrefabPath = PrefabPath;

            return newClone;
		}

        public GDEEnemyData DeepClone()
		{
			GDEEnemyData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_ID()
        {
            GDEDataManager.ResetToDefault(_key, IDKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(IDKey, out _ID);
        }

        public void Reset_MaxHP()
        {
            GDEDataManager.ResetToDefault(_key, MaxHPKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(MaxHPKey, out _MaxHP);
        }

        public void Reset_MoveVec()
        {
            GDEDataManager.ResetToDefault(_key, MoveVecKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(MoveVecKey, out _MoveVec);
        }

        public void Reset_AlertRange()
        {
            GDEDataManager.ResetToDefault(_key, AlertRangeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(AlertRangeKey, out _AlertRange);
        }

        public void Reset_AtkRange()
        {
            GDEDataManager.ResetToDefault(_key, AtkRangeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(AtkRangeKey, out _AtkRange);
        }

        public void Reset_AtkInterval()
        {
            GDEDataManager.ResetToDefault(_key, AtkIntervalKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(AtkIntervalKey, out _AtkInterval);
        }

        public void Reset_HurtProtect()
        {
            GDEDataManager.ResetToDefault(_key, HurtProtectKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(HurtProtectKey, out _HurtProtect);
        }

        public void Reset_Mass()
        {
            GDEDataManager.ResetToDefault(_key, MassKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(MassKey, out _Mass);
        }

        public void Reset_PrefabPath()
        {
            GDEDataManager.ResetToDefault(_key, PrefabPathKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(PrefabPathKey, out _PrefabPath);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, IDKey);
            GDEDataManager.ResetToDefault(_key, MoveVecKey);
            GDEDataManager.ResetToDefault(_key, MaxHPKey);
            GDEDataManager.ResetToDefault(_key, AlertRangeKey);
            GDEDataManager.ResetToDefault(_key, AtkRangeKey);
            GDEDataManager.ResetToDefault(_key, AtkIntervalKey);
            GDEDataManager.ResetToDefault(_key, HurtProtectKey);
            GDEDataManager.ResetToDefault(_key, MassKey);
            GDEDataManager.ResetToDefault(_key, PrefabPathKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
